SOCIAL-SITE : all functionality are updated related to `group` and `follow/unfollow` button . Need attention to fix some issue
ogniloud/MADR pull request #111
Opened 2024-04-15 17:51 UTC by benmasud

…inor errors

2024-04-15 18:07 UTC, benmasud commented on madr_web_app/src/components/Main-Page/MainPage.js
> +                if (user.isFollowing) {
@pelageech   посмотри сюда, что-то не так с `is Following` . **Это не работает**. В первый раз, когда ты ищеш пользователя (на которого ты никогда не подписывались), ты можешь нажать кнопку «Следовать», чтобы подписаться на этого пользователя, и это работает отлично, а также в то же время ты можешь отписаться от пользователя (потому что кнопка меняется). Итак, проблема в том, что как только ты закроешь поиск и повторить попытку, это не сработает, потому что на этот раз ` isFollowing=false` (даже если ты уже подписаны на него), поэтому предполагается, что это `isFollowing = true` (и кнопка надо отписаться)

_ps. Я несколько раз пытался его отладить, и вроде все в порядке, с серверной частью проблем нет, думаю, проблема в этом, но я не могу понять, что здесь не так"_

2024-04-17 13:16 UTC, pelageech commented on madr_web_app/src/components/Main-Page/MainPage.js
> +                    setGroupCreationSuccess('Group created successfully!');
Не знаю, чем мешает response. Его можно просто игнорировать.

2024-04-17 13:18 UTC, pelageech commented on madr_web_app/src/components/Main-Page/MainPage.js
> +                if (user.isFollowing) {
Сейчас посмотрю, что можно сделать

2024-04-17 14:21 UTC, benmasud commented on madr_web_app/src/components/Main-Page/MainPage.js
> +                    setGroupCreationSuccess('Group created successfully!');
@pelageech  из-за этого группы не загружаются, не могу игнорировать
![image](https://github.com/ogniloud/MADR/assets/69720999/9f5dfa8f-b451-4e95-bb81-4a2932894442)

2024-04-17 14:33 UTC, pelageech requested changes

2024-04-17 14:33 UTC, pelageech commented on .gitignore
> +MADR Frontend/.pnp.js
вернуть прежнее название папки

2024-04-18 02:29 UTC, pelageech commented on madr_web_app/src/App Components/Page-Components/Social Site Components/social_group.js
> +const SocialGroup = ({ userId }) => {
Здесь передается underfined. Проверь, почему так

2024-04-18 02:31 UTC, pelageech requested changes

2024-04-18 02:31 UTC, pelageech commented on madr_web_app/src/App.js
> +            <Route path="/mainpage/social_group/:group_id" element={<SocialGroupDetail />} />
Почему `mainpage/`?

2024-04-18 02:31 UTC, pelageech commented on madr_web_app/src/App Components/Page-Components/Social Site Components/social_group.js
> +                            <h3>Group Name: {group.name}</h3>
А добавь ещё вывод `group_id`

2024-04-18 05:17 UTC, benmasud commented on madr_web_app/src/App.js
> +            <Route path="/mainpage/social_group/:group_id" element={<SocialGroupDetail />} />
`mainpage/` это parents страница, но это не имеет значения, ну всегда можешь изменить

2024-04-21 10:43 UTC, pelageech requested changes
![image](https://github.com/ogniloud/MADR/assets/91509036/e0094777-120d-444a-983b-fbcce75cfc99)
не работает в интернете

```

> madr_web_app@0.1.0 start
> react-scripts start

(node:25) [DEP_WEBPACK_DEV_SERVER_ON_AFTER_SETUP_MIDDLEWARE] DeprecationWarning: 'onAfterSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:25) [DEP_WEBPACK_DEV_SERVER_ON_BEFORE_SETUP_MIDDLEWARE] DeprecationWarning: 'onBeforeSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
Starting the development server...

Failed to compile.

Module not found: Error: You attempted to import /app/node_modules/react-refresh/runtime.js which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.
You can either move it inside src/, or add a symlink to it from project's node_modules/.
WARNING in [eslint] 
src/App Components/Page-Components/API-Components/apiFunctions_browse_cards.js
  Line 1:8:    'React' is defined but never used             no-unused-vars
  Line 1:16:   'useEffect' is defined but never used         no-unused-vars
  Line 1:27:   'useRef' is defined but never used            no-unused-vars
  Line 1:35:   'useState' is defined but never used          no-unused-vars
  Line 2:9:    'Link' is defined but never used              no-unused-vars
  Line 2:15:   'Route' is defined but never used             no-unused-vars
  Line 2:22:   'Routes' is defined but never used            no-unused-vars
  Line 2:30:   'useNavigate' is defined but never used       no-unused-vars
  Line 6:1:    Block is redundant                            no-lone-blocks
  Line 15:15:  'user_id' is assigned a value but never used  no-unused-vars
  Line 21:38:  Unexpected template string expression         no-template-curly-in-string
  Line 72:38:  Unexpected template string expression         no-template-curly-in-string
  Line 96:38:  Unexpected template string expression         no-template-curly-in-string
  Line 115:1:  Block is redundant                            no-lone-blocks

src/App Components/Page-Components/API-Components/apiFunctions_decks.js
  Line 4:1:     Block is redundant                     no-lone-blocks
  Line 8:13:    Unexpected template string expression  no-template-curly-in-string
  Line 23:1:    Block is redundant                     no-lone-blocks
  Line 27:1:    Block is redundant                     no-lone-blocks
  Line 32:38:   Unexpected template string expression  no-template-curly-in-string
  Line 53:38:   Unexpected template string expression  no-template-curly-in-string
  Line 78:38:   Unexpected template string expression  no-template-curly-in-string
  Line 102:38:  Unexpected template string expression  no-template-curly-in-string
  Line 124:38:  Unexpected template string expression  no-template-curly-in-string
  Line 147:38:  Unexpected template string expression  no-template-curly-in-string
  Line 168:1:   Block is redundant                     no-lone-blocks

src/App Components/Page-Components/API-Components/apiFunctions_exe_cards.js
  Line 1:8:    'React' is defined but never used               no-unused-vars
  Line 1:16:   'useEffect' is defined but never used           no-unused-vars
  Line 1:27:   'useRef' is defined but never used              no-unused-vars
  Line 1:35:   'useState' is defined but never used            no-unused-vars
  Line 2:9:    'Link' is defined but never used                no-unused-vars
  Line 2:15:   'Route' is defined but never used               no-unused-vars
  Line 2:22:   'Routes' is defined but never used              no-unused-vars
  Line 2:30:   'useNavigate' is defined but never used         no-unused-vars
  Line 6:1:    Block is redundant                              no-lone-blocks
  Line 33:38:  Unexpected template string expression           no-template-curly-in-string
  Line 55:38:  Unexpected template string expression           no-template-curly-in-string
  Line 74:7:   'getUserId' is assigned a value but never used  no-unused-vars
  Line 83:1:   Block is redundant                              no-lone-blocks
  Line 87:38:  Unexpected template string expression           no-template-curly-in-string
  Line 108:1:  Block is redundant                              no-lone-blocks

src/App Components/Page-Components/API-Components/apiFunctions_groups.js
  Line 3:38:   Unexpected template string expression  no-template-curly-in-string
  Line 27:38:  Unexpected template string expression  no-template-curly-in-string
  Line 50:38:  Unexpected template string expression  no-template-curly-in-string
  Line 72:38:  Unexpected template string expression  no-template-curly-in-string

src/App Components/Page-Components/API-Components/apiFunctions_main_feeds.js
  Line 4:1:     Block is redundant                     no-lone-blocks
  Line 8:38:    Unexpected template string expression  no-template-curly-in-string
  Line 25:38:   Unexpected template string expression  no-template-curly-in-string
  Line 63:38:   Unexpected template string expression  no-template-curly-in-string
  Line 81:38:   Unexpected template string expression  no-template-curly-in-string
  Line 103:38:  Unexpected template string expression  no-template-curly-in-string
  Line 124:1:   Block is redundant                     no-lone-blocks
  Line 127:1:   Block is redundant                     no-lone-blocks
  Line 132:38:  Unexpected template string expression  no-template-curly-in-string
  Line 157:42:  Unexpected template string expression  no-template-curly-in-string
  Line 175:38:  Unexpected template string expression  no-template-curly-in-string
  Line 190:1:   Block is redundant                     no-lone-blocks

src/App Components/Page-Components/Decks/Browse Cards/AllWords.js
  Line 21:8:   React Hook useEffect has a missing dependency: 'loadFlashcards'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
  Line 63:11:  'getUserId' is assigned a value but never used                                                                     no-unused-vars

src/App Components/Page-Components/Decks/DeckDetail.js
  Line 17:11:   'navigate' is assigned a value but never used                                                                                             no-unused-vars
  Line 18:12:   'deckToDelete' is assigned a value but never used                                                                                         no-unused-vars
  Line 18:26:   'setDeckToDelete' is assigned a value but never used                                                                                      no-unused-vars
  Line 29:8:    React Hook useEffect has missing dependencies: 'handleShare' and 'handleSharedGroup'. Either include them or remove the dependency array  react-hooks/exhaustive-deps
  Line 97:40:   Unexpected mix of '&&' and '||'. Use parentheses to clarify the intended order of operations                                              no-mixed-operators
  Line 101:23:  Unexpected mix of '&&' and '||'. Use parentheses to clarify the intended order of operations                                              no-mixed-operators
  Line 101:23:  Unexpected mix of '||' and '&&'. Use parentheses to clarify the intended order of operations                                              no-mixed-operators
  Line 101:45:  Unexpected mix of '||' and '&&'. Use parentheses to clarify the intended order of operations                                              no-mixed-operators
  Line 115:38:  Unexpected mix of '&&' and '||'. Use parentheses to clarify the intended order of operations                                              no-mixed-operators
  Line 120:64:  Unexpected mix of '&&' and '||'. Use parentheses to clarify the intended order of operations                                              no-mixed-operators
  Line 127:43:  Unexpected mix of '&&' and '||'. Use parentheses to [...]

2024-04-25 04:52 UTC, merged