Handlers for flashcard deck service
ogniloud/MADR pull request #16
Opened 2023-11-08 08:38 UTC by pelageech

2023-11-09 15:23 UTC, pelageech commented
хз почему другие файлы поменялись, мне казалось на rebase они не должны появляться как изменённые

2023-11-11 07:07 UTC, peyuaa requested changes

2023-11-11 07:07 UTC, peyuaa commented on internal/flashcards/handlers/service.go
> +	if r.Method != http.MethodPut {
вроде chi-router не должен вообще роутить сюда методы, которые не совпадают с типом запроса. Типо стандартный роутер все подряд роутил и надо было проверять отдельно внутри тип запроса, но с chi так вроде не надо. На всякий случай запусти и проверь.

2023-11-11 07:07 UTC, peyuaa commented on internal/flashcards/handlers/service.go
> +	var err error
а в чем смысл тут объявлять err

2023-11-11 07:07 UTC, peyuaa commented on internal/flashcards/handlers/service.go
> +	if err := ioutil.FromJSON(&reqBody, r.Body); err != nil {
и потом тут опять его объявлять через :=, а не =

2023-11-11 07:07 UTC, peyuaa commented on internal/flashcards/handlers/service.go
> +	if err := ioutil.FromJSON(&reqBody, r.Body); err != nil {
типо просто лишний раз переаллоцируем память

2023-11-11 07:07 UTC, peyuaa commented on internal/flashcards/handlers/service.go
> +	if r.Method != http.MethodDelete {
аналогично с chi-router эта проверка не нужна, он в саммом роутере это все проверяет насколько я помню

2023-11-11 07:07 UTC, peyuaa commented on internal/flashcards/handlers/service.go
> +	if r.Method != http.MethodDelete {
ну и ко всем остальным проверкам аналогично, чтобы везде не писать коммент

2023-11-11 07:08 UTC, peyuaa commented on internal/flashcards/handlers/service.go
> +	if r.Method != http.MethodPut {
https://github.com/ogniloud/MADR/blob/34f6503333d5399d4249249130bb9c4a0e039594/cmd/api-server/main.go#L51

2023-11-11 07:17 UTC, pelageech commented on internal/flashcards/handlers/service.go
> +	var err error
не помню, кстати. Вроде нужно было, но щас можно убрать реально

2023-11-11 07:19 UTC, pelageech commented on internal/flashcards/handlers/service.go
> +	if err := ioutil.FromJSON(&reqBody, r.Body); err != nil {
не думаю, что какая-то жёсткая утечка или уменьшение производительности из-за аллокации будет
Переменная почти сразу мусорной станет

2023-11-11 07:22 UTC, merged