PSQL
ogniloud/MADR pull request #24
Opened 2023-11-11 09:25 UTC by pelageech

2023-11-12 10:30 UTC, peyuaa requested changes

2023-11-12 10:30 UTC, peyuaa commented on internal/flashcards/handlers/service.go
> +	ids, err := d.s.GetFlashcardsIdByDeckId(context.TODO(), reqBody.DeckId)
так а почему ты context реквеста не прокидываешь? https://pkg.go.dev/net/http#Request.Context

2023-11-12 10:30 UTC, peyuaa commented on internal/flashcards/handlers/service.go
> +		card, err := d.s.GetFlashcardById(context.TODO(), ids[i])
https://pkg.go.dev/net/http#Request.Context

2023-11-12 10:30 UTC, peyuaa commented on internal/flashcards/handlers/service.go
> +	id, err := d.s.PutAllFlashcards(context.TODO(), reqBody.DeckId, []models.Flashcard{{
https://pkg.go.dev/net/http#Request.Context

2023-11-12 10:30 UTC, peyuaa commented on internal/flashcards/handlers/service.go
> +	_, err = d.s.PutAllUserLeitner(context.TODO(), []models.UserLeitner{{
https://pkg.go.dev/net/http#Request.Context

2023-11-12 10:30 UTC, peyuaa commented on internal/flashcards/handlers/service.go
> +	err := d.s.DeleteFlashcardFromDeck(context.TODO(), reqBody.FlashcardId)
https://pkg.go.dev/net/http#Request.Context

2023-11-12 10:30 UTC, peyuaa commented on internal/flashcards/models/exercises.go
> +type Matching struct {
комментарии

2023-11-12 10:30 UTC, peyuaa commented on internal/flashcards/models/exercises.go
> +type Text struct {
комментарии

2023-11-12 10:30 UTC, peyuaa commented on internal/flashcards/services/deck/service.go
> +	decks, err := s.GetDecksByUserId(context.TODO(), id)
https://pkg.go.dev/net/http#Request.Context

2023-11-12 10:30 UTC, peyuaa commented on internal/flashcards/services/deck/service.go
> +	if id, err = s.PutNewDeck(context.TODO(), cfg); err != nil {
https://pkg.go.dev/net/http#Request.Context

2023-11-12 10:30 UTC, peyuaa commented on internal/flashcards/services/deck/service.go
> +	if _, err := s.PutAllFlashcards(context.TODO(), cfg.DeckId, flashcards); err != nil {
https://pkg.go.dev/net/http#Request.Context

2023-11-12 10:30 UTC, peyuaa commented on internal/flashcards/services/deck/service.go
> +	if err := s.DeleteUserDeck(context.TODO(), userId, deckId); err != nil {
https://pkg.go.dev/net/http#Request.Context

2023-11-12 10:30 UTC, peyuaa commented on internal/flashcards/services/deck/service.go
> +	info, err := s.GetUserInfo(context.TODO(), uid)
https://pkg.go.dev/net/http#Request.Context

2023-11-14 03:14 UTC, pelageech commented on internal/flashcards/models/exercises.go
> +type Matching struct {
эт от ребэйза досталось

2023-11-14 03:14 UTC, pelageech commented on internal/flashcards/models/exercises.go
> +type Text struct {
ребэйз, не моё

2023-11-14 03:36 UTC, pelageech commented
По итогу добавил проброс контекста через все сервисы

2023-11-14 03:41 UTC, pelageech commented on internal/flashcards/models/exercises.go
> +type Matching struct {
добавил

2023-11-14 03:41 UTC, pelageech commented on internal/flashcards/models/exercises.go
> +type Text struct {
добавил

2023-11-19 15:42 UTC, peyuaa approved these changes

2023-11-19 15:44 UTC, merged