Flashcards v1.1
ogniloud/MADR pull request #7
Opened 2023-10-25 11:56 UTC by pelageech

Some in-memory items are supposed to be moved to DB

2023-11-03 16:26 UTC, peyuaa requested changes
По сваггеру если что он хорошо объясняет: https://www.youtube.com/live/07XhTqE-j8k?si=T0dZyfi3QGC3jMUX

2023-11-03 16:26 UTC, peyuaa commented on pkg/flashcards/handlers/handler.go
> +func (d Deck) LoadDecks(w http.ResponseWriter, r *http.Request) {
Мб добавишь сваггер? Типо посмотри как у меня сделано и сгенерь, по идее это недолго, если разобраться + полезно будет на будущее уметь сваггер генерировать

2023-11-03 16:26 UTC, peyuaa commented on pkg/flashcards/handlers/handler.go
> +func (d Deck) LoadDecks(w http.ResponseWriter, r *http.Request) {
Типо на все публичные endpoints добавить

2023-11-03 16:26 UTC, peyuaa commented on pkg/flashcards/handlers/handler.go
> +func (d Deck) LoadDecks(w http.ResponseWriter, r *http.Request) {
https://github.com/ogniloud/MADR/blob/cbb224076fd38ed1024b52a9e35be9138c4f0921/internal/handlers/post.go#L11

2023-11-03 16:26 UTC, peyuaa commented on pkg/flashcards/handlers/handler.go
> +	dec := json.NewDecoder(r.Body)
Я в package models вынес всё это создание декодеров. Посмотри эту строку https://github.com/ogniloud/MADR/blob/cbb224076fd38ed1024b52a9e35be9138c4f0921/internal/handlers/post.go#L45

Мне кажется лучше везде одинакового стиля придерживаться

2023-11-03 16:26 UTC, peyuaa commented on pkg/flashcards/handlers/handler.go
> +	dec := json.NewDecoder(r.Body)
С енкодером та же тема, есть в package models. Вмержь в эту ветку master

2023-11-03 16:26 UTC, peyuaa commented on pkg/flashcards/handlers/handler.go
> +	enc := json.NewEncoder(w)
https://github.com/ogniloud/MADR/blob/cbb224076fd38ed1024b52a9e35be9138c4f0921/internal/handlers/post.go#L126

2023-11-03 16:26 UTC, peyuaa commented on pkg/flashcards/handlers/handler.go
> +		d.ew.Error(w, err.Error(), http.StatusInternalServerError)
Аналогично со всеми error, предлагаю использовать дженерик-функцию, которую я написал, чтобы у нас было стандартизированный возврат всех ошибок https://github.com/ogniloud/MADR/blob/cbb224076fd38ed1024b52a9e35be9138c4f0921/internal/handlers/post.go#L121

2023-11-03 16:26 UTC, peyuaa commented on pkg/flashcards/handlers/handler.go
> +		d.ew.Error(w, err.Error(), http.StatusInternalServerError)
И вообще если это на самом деле InternalServerError, то это обязательно надо логгировать + возвращать пользователю заглушку как я делаю.

2023-11-03 16:26 UTC, peyuaa commented on pkg/flashcards/handlers/handler.go
> +		d.ew.Error(w, err.Error(), http.StatusInternalServerError)
Типо InternalServerError это когда что-то пошло совсем не по плану. Мб тут другой код ошибки нужен, подумай

2023-11-03 16:26 UTC, peyuaa commented on pkg/flashcards/cache/cache.go
> +type Cache = *sync.Map
Го ко всем экспортируемым структурам делать комментарии, хотя бы с помощью Github Copilot их сгенерировать, это быстро

2023-11-03 16:26 UTC, peyuaa commented on pkg/flashcards/cache/cache.go
> +type CachedRandom []models.FlashcardId
Комментарий

2023-11-03 16:26 UTC, peyuaa commented on pkg/flashcards/cache/cache.go
> +package cache
Package level коммент какой-нибудь про то что делает package

2023-11-03 16:26 UTC, peyuaa commented on pkg/flashcards/cache/cache.go
> +package cache
В таких случаях заводят иногда специально файл doc.go, если коммент большой, но тут можно прямо здесь написать коротенький

2023-11-03 16:26 UTC, peyuaa commented on pkg/flashcards/cache/cache.go
> +package cache
> // Package path implements utility routines for manipulating slash-separated
> // paths.
> //
> // The path package should only be used for paths separated by forward
> // slashes, such as the paths in URLs. This package does not deal with
> // Windows paths with drive letters or backslashes; to manipulate
> // operating system paths, use the [path/filepath] package.
> package path

2023-11-03 16:26 UTC, peyuaa commented on pkg/flashcards/cache/cache.go
> +package cache
https://tip.golang.org/doc/comment

2023-11-03 16:26 UTC, peyuaa commented on pkg/flashcards/handlers/handler.go
> +type ErrorWriter interface {
Ну вот я советую юзать то, что я уже в master написал, чтобы не дублировать способы врайтов ошибок

2023-11-03 16:26 UTC, peyuaa commented on pkg/flashcards/handlers/handler.go
> +type Deck struct {
Комментарий

2023-11-03 16:26 UTC, peyuaa commented on pkg/flashcards/models/api.go
> +type LoadDecksRequest struct {
комментарий

2023-11-03 16:26 UTC, peyuaa commented on pkg/flashcards/models/api.go
> +type LoadDecksResponse struct {
комментарий

2023-11-03 16:26 UTC, peyuaa commented on pkg/flashcards/models/flashcards.go
> +type DeckConfig struct {
комментарий

2023-11-03 16:26 UTC, peyuaa commented on pkg/flashcards/models/flashcards.go
> +type UserInfo struct {
комментарий

2023-11-03 16:26 UTC, peyuaa commented on pkg/flashcards/models/flashcards.go
> +type Flashcard struct {
комментарий

2023-11-03 16:26 UTC, peyuaa commented on pkg/flashcards/models/flashcards.go
> +type UserLeitner struct {
комментарий

2023-11-03 16:26 UTC, peyuaa commented on pkg/flashcards/models/flashcards.go
> +type UserLeitner struct {
ну и в целом всем экспортируемым лучше писать, потому что они в godoc при релизе показываются

2023-11-03 16:26 UTC, peyuaa commented on pkg/flashcards/services/deck/service_test.go
> +	"github.com/stretchr/testify/assert"
разделить импорты

2023-11-03 16:26 UTC, peyuaa commented on pkg/flashcards/services/study/study_service.go
> +	p     []float32 // for each i => 0 <= p[i] < 1
что-то на умном, что-то непонятное, нужно объяснение тому кто это потом будет читать. Что такое p, что такое fserv, что такое StudyService

2023-11-03 16:26 UTC, peyuaa commented on pkg/flashcards/services/study/study_service.go
> +	return 0, fmt.Errorf("no cards")
мб в константы ошибки вынести или в переменные

2023-11-03 16:26 UTC, peyuaa commented on pkg/flashcards/services/study/study_service_test.go
> +	"github.com/stretchr/testify/assert"
разделить испорты

2023-11-03 16:26 UTC, peyuaa commented on pkg/flashcards/storage/storage.go
> +	GetUserInfo(uid models.UserId) (models.UserInfo, error)
почему у каких-то интерфейсов есть коменты, а у каких-то нет.  + мне кажется надо во всем проекте писать комментарии на одном языке, а то в одних местах на русском, в других на английском

2023-11-04 06:31 UTC, pelageech commented on pkg/flashcards/handlers/handler.go
> +func (d Deck) LoadDecks(w http.ResponseWriter, r *http.Request) {
Добавлю в новой ветке

2023-11-04 06:32 UTC, pelageech commented on pkg/flashcards/handlers/handler.go
> +type ErrorWriter interface {
в следующей ветке

2023-11-04 06:36 UTC, pelageech commented on pkg/flashcards/models/api.go
> +type LoadDecksRequest struct {
в следующей ветке

2023-11-04 06:36 UTC, pelageech commented on pkg/flashcards/models/api.go
> +type LoadDecksResponse struct {
в следующей ветке

2023-11-04 06:37 UTC, pelageech commented on pkg/flashcards/handlers/handler.go
> +		d.ew.Error(w, err.Error(), http.StatusInternalServerError)
d cktle.otq dtnrt

2023-11-04 06:38 UTC, pelageech commented on pkg/flashcards/handlers/handler.go
> +	enc := json.NewEncoder(w)
в следующей ветке

2023-11-04 06:38 UTC, pelageech commented on pkg/flashcards/handlers/handler.go
> +	dec := json.NewDecoder(r.Body)
в следующей ветке

2023-11-06 09:41 UTC, peyuaa commented on internal/flashcards/services/deck/service.go
> +	storage.Storage
ну я в целом эмбедингом особо не пользовался и я не уверен, что это лучше, чем отдельное поле. Но если ты так считаешь, то ок

2023-11-06 09:41 UTC, peyuaa commented on internal/flashcards/services/deck/service.go
> +		decks := decksAny.(models.Decks)
decks, ok := decksAny.(models.Decks)
if !ok {

}

Не надо проверку добавлять, раз уж мы конвертим?

2023-11-06 09:41 UTC, peyuaa commented on internal/flashcards/services/deck/service.go
> +	s.c.Store(id, decks)
подозреваю что когда будем реальное хранилище использовать, то оно может вернуть ошибку и лучше заранее это в сигнатуре предусмотреть

2023-11-06 15:37 UTC, peyuaa commented on internal/flashcards/services/deck/service.go
> +		if decks, ok := decksAny.(models.Decks); ok {
А если не ok, то просто продолжаем дальше исполняться? так и задумано или я просто логику не выкупаю

2023-11-06 15:37 UTC, peyuaa commented on internal/flashcards/services/deck/service.go
> +		s.logger.Errorf("cache store failed: %v", err)
ну тут мы получается логируем ошибку и продолжаем дальше исполняться, наверное надо error вернуть тому, кто эту функцию вызвал

2023-11-06 15:37 UTC, peyuaa commented on internal/flashcards/services/study/study_service_test.go
> +	"github.com/charmbracelet/log"
порядок импортов

2023-11-06 15:37 UTC, peyuaa commented on internal/flashcards/services/study/study_service_test.go
> +	serv := deck.NewService(t.m, cache.New(), log.New(io.Discard))
почему io.Discard? Это же потом все переделывать придется

2023-11-06 15:37 UTC, peyuaa commented on internal/flashcards/services/deck/service_test.go
> +	"github.com/charmbracelet/log"
порядок импортов

2023-11-06 15:37 UTC, peyuaa commented on internal/flashcards/services/deck/service.go
> +	"github.com/charmbracelet/log"
порядок импортов

2023-11-06 15:37 UTC, peyuaa commented on internal/flashcards/services/deck/service_test.go
> +	l.s = deck.NewService(s, cache.New(), log.New(io.Discard))
тут тоже почему io.Discard

2023-11-07 13:19 UTC, peyuaa approved these changes

2023-11-07 14:04 UTC, merged